### ISSUE TITLE
robot position and joint angles does not get updated

### ISSUE THREAD

**Issue by Dhiraj100892** [RethinkRobotics/sawyer_moveit#27]
Hi, 

  I'm using (group =) moveit_commander.MoveGroupCommander("right_arm") to get the group. I'm able to access the group. But when I do group.get_current_joint_values() , I get all the values equal to zero, irrespective of the configuration of the robot. Also when I try to do group.get_current_pose().pose, I get the pose corresponding to the zero joint angles in any configuration of the arm. But the rviz moveit visualizer is working fine ( it is showing the present configuration of the robot).

  Can you guide me how to resolve this issue?

**Comment by IanTheEngineer** [comment]
Based on your description, it seems you're running into the remapping of `/joint_states` to `/robot/joint_states` that moveit_commander requires. See [this thread](https://groups.google.com/a/rethinkrobotics.com/d/msg/brr-users/BKot64nTkkA/tQk4SOqdKyEJ) of brr-users-group for more details:

`rosrun moveit_commander moveit_commander_cmdline.py  joint_states:=/robot/joint_states`
