### ISSUE TITLE
moveit execution fails on real robot

### ISSUE THREAD

**Issue by GavinStrunk** [RethinkRobotics/sawyer_moveit#28]
I am using Ubuntu 16.04 and ros kinetic.  I am able to move the sawyer with the intera sdk examples, but when I use the execute button after it has created a plan in the rviz gui it fails with this message:

[ WARN] [1505497768.668273664]: Failed to validate trajectory: couldn't receive full current joint state within 1s
[ INFO] [1505497768.668366775]: Execution completed: ABORTED

I double checked and the robot is enabled and the joint_trajectory_action_server is also running.  Does anyone know why this won't execute on the real robot?

**Comment by IanTheEngineer** [comment]
Likely, your Sawyer has moved beyond an epsilon of the initial joint angles of the planning scene. I would recommend resetting your initial state to your robots current configuration, and replan. You can also do this in the MoveIt RViz GUI. This functionality is actually a new feature of MoveIt in Kinetic:
https://github.com/ros-planning/moveit/pull/63
and the commit:
https://github.com/ros-planning/moveit/commit/ce659702dc12b34952476a8a8af7ebc8fdab2cfd
